# Generated by Django 3.2 on 2022-12-02 18:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ficha', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('logo', models.ImageField(blank=True, help_text='*Logotipos con altura de 120px y ancho de 300px*', null=True, upload_to='logo/', verbose_name='Logo de institución')),
                ('logo_email', models.ImageField(blank=True, help_text='*Logotipos con altura de 120px y ancho de 300px*', null=True, upload_to='logo/', verbose_name='Logo que se mostrará en correos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
