# Generated by Django 3.2 on 2022-12-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20221202_1350'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustes',
            name='logo_email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='ajustes',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo de institución'),
        ),
        migrations.AlterField(
            model_name='ajustes',
            name='subtitulo',
            field=models.CharField(default='LABSOL', max_length=100, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='ajustes',
            name='titulo',
            field=models.CharField(default='Sistema de Control y Seguimiento de Correspondencias', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.area', verbose_name='Area'),
        ),
    ]
