# Generated by Django 3.2 on 2022-12-02 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='pdf_dependencia',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='estatus',
            field=models.BooleanField(default=False, verbose_name='Estátus'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_recibido',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha y Firma de quién recibe'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_ficha',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='No. de Ficha'),
        ),
    ]
